---
driver:
  name: ec2
  security_group_ids: [ "sg-bc5713d9" ] #OpsWorks - nodejs
  region: ap-northeast-1
  availability_zone: ap-northeast-1a
  require_chef_omnibus: true

provisioner:
  name: chef_solo

transport:
  username: holyshared
  ssh_key: <%= File.expand_path("~/.ssh/#{ENV['AWS_SSH_KEY_ID']}.pem") %>

platforms:
  - name: AmazonLinux-201509
    driver:
      image_id: ami-393c1957
    transport:
      username: ec2-user
suites:
  - name: default
    run_list:
      - recipe[cachectld::default]
    attributes:
